version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: shop_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KhongCoPassDau123!
      MYSQL_DATABASE: ShopTechDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: